version: '3.9'

services:

  proxy:
    image: traefik:v2.11.0
    restart: always
    ports:
      - 80:80
      - 443:443

    command:
      - --providers.docker=true
      - --providers.docker.network=proxy
      - --providers.docker.exposedByDefault=true  

      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443 

      - --certificatesresolvers.default.acme.tlschallenge=true
      - --certificatesresolvers.default.acme.email={{ACME_EMAIL}}
      - --certificatesresolvers.default.acme.storage=/letsencrypt/acme.json

    labels:
      # Auth
      - traefik.http.middlewares.traefik_api_auth.basicauth.users={{TRAEFIK_LOGIN}}

      # HTTP -> HTTPS
      - traefik.http.routers.traefik_dashboard_http.entrypoints=web
      - traefik.http.routers.traefik_dashboard_http.rule=Host(`{{TRAEFIK_DASHBOARD_DOMAIN}}`) 
      - traefik.http.routers.traefik_dashboard_http.middlewares=traefik_dashboard_redirect
      - traefik.http.middlewares.traefik_dashboard_redirect.redirectscheme.scheme=https

      # HTTPS -> Dashboard Frontend Service
      - traefik.http.routers.traefik_dashboard_https.entrypoints=websecure
      - traefik.http.routers.traefik_dashboard_https.rule=Host(`{{TRAEFIK_DASHBOARD_DOMAIN}}`)
      - traefik.http.routers.traefik_dashboard_https.tls.certresolver=default
      - traefik.http.routers.traefik_dashboard_https.service=dashboard@internal

      # HTTPS -> Dashboard Backend Service
      - traefik.http.routers.traefik_dashboard_api_https.entrypoints=websecure
      - traefik.http.routers.traefik_dashboard_api_https.rule=Host(`{{TRAEFIK_DASHBOARD_DOMAIN}}`) && Path(`/api`)
      - traefik.http.routers.traefik_dashboard_api_https.tls.certresolver=default
      - traefik.http.routers.traefik_dashboard_api_https.middlewares=traefik_api_auth
      - traefik.http.routers.traefik_dashboard_api_https.service=api@internal

      # HTTPS -> Default API Service
      - traefik.http.routers.traefik_api_https.entrypoints=websecure
      - traefik.http.routers.traefik_api_https.rule=Host(`{{TRAEFIK_API_DOMAIN}}`)
      - traefik.http.routers.traefik_api_https.tls.certresolver=default
      - traefik.http.routers.traefik_api_https.middlewares=traefik_api_auth
      - traefik.http.routers.traefik_api_https.service=api@internal

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    
    networks:
      - proxy

  portainer:
    image: portainer/portainer-ce:2.19.4
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data

    networks:
      - proxy

    labels:
      # Service
      - traefik.http.services.portainer_service.loadbalancer.server.port=9000

      # HTTP -> HTTPS
      - traefik.http.routers.portainer_http.entrypoints=web
      - traefik.http.routers.portainer_http.rule=Host(`{{PORTAINER_DOMAIN}}`)
      - traefik.http.routers.portainer_http.middlewares=portainer_redirect
      - traefik.http.middlewares.portainer_redirect.redirectscheme.scheme=https

      # HTTPS -> Service
      - traefik.http.routers.portainer_https.entrypoints=websecure
      - traefik.http.routers.portainer_https.rule=Host(`{{PORTAINER_DOMAIN}}`)
      - traefik.http.routers.portainer_https.tls.certresolver=default 
      - traefik.http.routers.portainer_https.service=portainer_service
      
networks:
  proxy:
    external: true  

